site_name: Getting started with mbed Device Connector
theme: readthedocs

pages:
- ['index.md', 'About this document']
- ['Connector-intro.md','Introduction to mbed Client']
- ['Quick-guide.md','Getting started']
- ['Further-reading.md','Further reading']




